src/classroom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vclass/', include('vclass.urls')),
    path('api/', include('vclass.api.urls'))
]
""" if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) """
     
if settings.DEBUG:
    urlpatterns= urlpatterns + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    urlpatterns= urlpatterns + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

src/vclass/api/urls.py
from django.urls import path,include
from vclass.api.views import (
    Teacher_register,
    User_logout,
    Student_register,
    get_class,
    get_class_details,
    make_classroom,
    pdfCreate,
    get_class_peoples,
    get_pdf,
    Check_images_AI
)
from rest_framework.authtoken.views import obtain_auth_token

app_name = "vclass"

urlpatterns = [
    path('registert', Teacher_register, name="teacher-register"),
    path('registers', Student_register, name="student-register"),
    path('login',obtain_auth_token, name="login"),
    path('logout',User_logout, name="logout"),
    path('ClassroomInfo',get_class, name="classroom"),
    path('ClassDetails',get_class_details, name="details"),
    path('ClassMake',make_classroom, name="Class-make"),
    path('PdfUpload',pdfCreate, name="Pdf-upload"),
    path('ClassPeople',get_class_peoples, name="peoples"),
    path('getPdf',get_pdf, name="pdf-return"),
    path('ai',Check_images_AI, name="image-verify"),
    #path('rest-auth/', include('rest_auth.urls')),
]

src/vclass/urls.py
from django.urls import path,reverse,include
from . import views
from django.contrib.auth.views import LoginView,LogoutView
from .views import (
     register,
    student_register,
    teacher_register,
    login_view,logout_view,
    Class_create_view,mail_sending,
    landing_view,student_view,teacher_view,
    joinclass_view, Student_class_detail_view,
    Teacher_class_detail_view,
    Student_profile_view,Student_update_view,
    pdf_create_view, people_view,
    task_view,task_detail_view,
    pdf_view, written_question,
    annotaion_view,
    recorded_question,
    check_view,
    show_questions_view
    )

app_name = 'portf'

urlpatterns = [
    path('student', student_view, name= 'student-home'),
    path('teacher', teacher_view, name= 'teacher-home'),
    path('teacher/<success>', teacher_view, name= 'teacher-home'),
    path('register/', register, name= 'register'),
    path('login/', login_view, name= 'login'),
    path('logout/', logout_view, name= 'logout'),
    path('student_register/', student_register.as_view(), name= 'student_register'),
    path('teacher_register/', teacher_register.as_view(), name= 'teacher_register'),
    path('class_create/', Class_create_view, name= 'class_creation'),
    path('class_join/', joinclass_view, name= 'class_join'),
    path('mailing/', mail_sending, name= 'mailing'),
    path('', landing_view, name= 'land'),
    path('Studentclass/<int:my_id>',Student_class_detail_view, name= 'student-class-view'),
    path('teacherclass/<int:my_id>' , Teacher_class_detail_view, name="teacher-class-view"),
    path('profile', Student_profile_view, name="student-profile"),
    path('update/<int:pk>', Student_update_view, name="student-update"),
    path('create/<int:my_id>', pdf_create_view, name="pdf-create"),
    path('people/<int:my_id>', people_view, name="people"),
    path('task/<int:my_id>', task_view, name="task"),
    path('taskdetail/<int:my_id>', task_detail_view, name="task-detail"),
    path('checking/<success>/<int:my_id>/', check_view, name="check"),
    path('viewer/<success>/<int:my_id>/', pdf_view, name="pdf-view"),
    path('written/<int:my_id>', written_question, name="written"),
    path('annotation/<int:my_id>', annotaion_view, name="annote"),
    path('recorded/<int:my_id>', recorded_question, name="recorded"),
    path('questions/', show_questions_view, name="questions"),
]

src/vclass/forms.py

from django import forms
from django.db.models import fields
from django.forms.widgets import ClearableFileInput, FileInput
from .models import Student,Teacher,User,Classroom,Class_Metarials
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.db import transaction
from django.forms import ImageField


class StudentForm(UserCreationForm):
    first_name = forms.CharField(required=True, widget= forms.TextInput())
    Last_name = forms.CharField(required=True,widget= forms.TextInput())
    Email = forms.EmailField(required=True,widget= forms.TextInput())
    Image = forms.ImageField( )
    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_Student = True

        user.save()
        student = Student.objects.create(user=user)
        student.First_name = self.cleaned_data.get('first_name')
        student.Last_name = self.cleaned_data.get('Last_name')
        student.Email_address=self.cleaned_data.get('Email')
        student.save()
        student.image = self.cleaned_data.get("Image")
        student.save()
        return user

class TeacherForm(UserCreationForm):
    first_name = forms.CharField(required=True, widget= forms.TextInput())
    Last_name = forms.CharField(required=True,widget= forms.TextInput( ))
    Email = forms.EmailField(required=True,widget= forms.TextInput())

    class Meta(UserCreationForm.Meta):
        model = User


    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_Teacher = True

        user.save()
        teacher = Teacher.objects.create(user=user)
        teacher.Email_address=self.cleaned_data.get('Email')
        teacher.First_name=self.cleaned_data.get('first_name')
        teacher.Last_name= self.cleaned_data.get('Last_name')
        teacher.save()
        return user

class loginform (AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(loginform, self).__init__(*args, **kwargs)

    username= forms.CharField(widget= forms.TextInput
                           (attrs={'placeholder':'Enter Your Username',
                           'class' : 'form-control'
                           }))
    password = forms.CharField(widget=forms.PasswordInput (
        attrs={'placeholder' : 'Enter Password','class' : 'form-control'}
    ))

class classcreation(forms.Form):
    Class_Name = forms.CharField(required=True)
    Subject = forms.CharField(required=True)
    Section = forms.IntegerField(required=True)

class classjoinform(forms.Form):
    code = forms.CharField(required=True)

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model=Student
        fields = ['First_name','Last_name','Email_address','image']

class pdfCreateForm(forms.ModelForm):
    Submit_Date= forms.DateField(label='Due Date', widget=forms.SelectDateWidget(
        attrs={'class': "input--style-6"}
    ))
    title = forms.CharField(max_length=80, widget=forms.TextInput(
        attrs={'class' : "input--style-6"}
    ))
    Description = forms.CharField(widget=forms.Textarea(
        attrs={'class' : "textarea--style-6"}
    ))
    
    class Meta:
        model = Class_Metarials
        fields = ('title','Description','Submit_Date','Pdf')

class questionCreateForm(forms.Form):

    Written= forms.CharField(widget=forms.Textarea(attrs={"rows":1, "cols":50, 
        'id' : "input"
    }))
    Tag = forms.CharField(required = False, widget=forms.NumberInput(attrs={
        'id' : 'value',
        'class' : 'hide'
    }))


src/vclass/api/views.py
from django.core.checks import messages
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view,permission_classes
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth import get_user_model, logout
from vclass.models import Classroom,Student,Teacher,User,Class_Metarials, image_verify
from vclass.functions import get_user,get_class
from vclass.api.serializers import (
    TeacherRegistrationSerializer,
    StudentRegistrationSerializer,
    getClassroomSerializer,
    getClassIDSerializer,
    makeClassroomSerilizer,
    pdfCreateSerilizer,
    getMetarialIDSerializer,
    ImageSerializer )
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from django.utils.crypto import get_random_string
from django.http import FileResponse
from wsgiref.util import FileWrapper
from django.http import HttpResponse
from classroom.settings import BASE_DIR
import face_recognition
import os, re, os.path,glob


@api_view(['POST', ])
@permission_classes([])
def Teacher_register(request):
    if request.method == 'POST':
        serializer = TeacherRegistrationSerializer(data=request.data)
        data = {}
        if serializer.is_valid():
            user = serializer.save()
            data['response'] = 'successfully registered new user.'
            #data['email'] = user.email
            data['username'] = user.username
            token = Token.objects.get(user=user).key
            data['token'] = token
        else:
            data = serializer.errors
        return Response(data)



@api_view(['POST', ])
#@authentication_classes([])
@permission_classes([])
def Student_register(request):
    if request.method == 'POST':
        serializer = StudentRegistrationSerializer(data=request.data)
        data = {}
        if serializer.is_valid():
            user = serializer.save()
            data['response'] = 'successfully registered new user.'
            #data['email'] = user.email
            data['username'] = user.username
            token = Token.objects.get(user=user).key
            data['token'] = token
        else:
            data = serializer.errors
        return Response(data)


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def User_logout(request):
    request.user.auth_token.delete()
    logout(request)
    return Response('User Logged out successfully')


@api_view(["POST"])
@permission_classes([])
def get_class(request):
    if request.method == 'POST':
        serializer = getClassroomSerializer(data=request.data)
        data = {}
        if serializer.is_valid():
           username = serializer.validated_data.get('username')
           #print(username)
           user = User.objects.get(username = username)

           if (user.is_Student == True):
               student = Student.objects.get(pk=user)
               classes = Classroom.objects.filter(Student=student.pk)
               data = classroomSender(classes)
           
           elif (user.is_Teacher == True):
               teacher = Teacher.objects.get(pk=user)
               classes = Classroom.objects.filter(Teacher=teacher.pk)
               data = classroomSender(classes)


        return Response(data)


def classroomSender(classes):
    data = {}
    count = classes.count()
    data['count'] = count
    if count > 0 :
        key1 = "classname"
        key2 = "subject"
        key3 = "section"
        key4 = "classId"
        data.setdefault(key1, [])
        data.setdefault(key3, [])
        data.setdefault(key2, [])
        data.setdefault(key4, [])
        for class_ in classes:
            classname = class_.Class_name
            subject = class_.Subject
            section = class_.section
            classId = class_.id

            data[key1].append(classname)
            data[key2].append(subject)
            data[key3].append(section)
            data[key4].append(classId)
    return data


@api_view(["POST"])
@permission_classes([])
def get_class_details(request):
    
    data = {}
    serializer = getClassIDSerializer(data=request.data)
    
    if serializer.is_valid():
        my_id = serializer.validated_data.get('ClassId')
        
        classroom = Classroom.objects.get(id=my_id)
        classname = classroom.Class_name

        #students = Student.objects.filter(classroom = classroom)
        #studentcounter = students.count()

        metarials = Class_Metarials.objects.filter(Classroom = classroom)
        count = metarials.count()

        data['count'] = count
        data['classname'] = classname
        if count > 0 :
            key1 = "title"
            key2 = "Submit_Date"
            key3 = "Description"
            key4 = "id"
            data.setdefault(key1, [])
            data.setdefault(key2, [])
            data.setdefault(key3, [])
            data.setdefault(key4, [])
            #print(BASE_DIR)
            

            for metarial in metarials:
                title = metarial.title
                date = metarial.Submit_Date
                description = metarial.Description
                mid = metarial.id
                #url = metarial.Pdf.url
                #file_dir = BASE_DIR + url
                #print(file_dir)
                #pdf_file = open(file_dir, 'rb')
                #response = FileResponse(pdf_file)
                #response = HttpResponse(FileWrapper(pdf_file), content_type='application/pdf')
            
                data[key1].append(title)
                data[key2].append(date)
                data[key3].append(description)
                data[key4].append(mid)
                        
    
    return Response(data)

@api_view(["POST"])
@permission_classes([])
def get_pdf(request):
    data = {}
    serializer = getMetarialIDSerializer(data=request.data)
    my_id = None
    if serializer.is_valid():
        my_id = serializer.validated_data.get('MetarialId')
        #data["my_id"]=my_id
    metarial = Class_Metarials.objects.get(id = my_id)
    url = metarial.Pdf.url
    file_dir = BASE_DIR + url
    pdf_file = open(file_dir, 'rb')
    response = HttpResponse(FileWrapper(pdf_file), content_type='application/pdf')

    return response
    


@api_view(["POST"])
@permission_classes([])
def get_class_peoples(request):
    data = {}
    serializer = getClassIDSerializer(data=request.data)
    if serializer.is_valid():
        my_id = serializer.validated_data.get('ClassId')
        classroom = Classroom.objects.get(id=my_id)
        students = Student.objects.filter(classroom = classroom)

        count = students.count()
        data['counter'] = count
        if count>0:
            key1 = "name"
            key2 = "email"
            data.setdefault(key1, [])
            data.setdefault(key2, [])
            for student in students:
                fname = student.First_name
                lname = student.Last_name
                name = fname + " " + lname
                email = student.Email_address

                data[key1].append(name)
                data[key2].append(email)

    return Response(data)




@api_view(["POST"])
@permission_classes([])
def make_classroom(request):
    Unique_code = get_random_string(length=6)
    data = {}
    serializer = makeClassroomSerilizer(data=request.data)
    if serializer.is_valid():
        username = serializer.validated_data.get('username')
        
        user = User.objects.get(username = username)
        
        if (user.is_Student == True):
            data['Invalid'] = "Invalid"
        elif (user.is_Teacher == True):
            Subject = serializer.validated_data.get('Subject')
            section = serializer.validated_data.get('section')
            class_name = serializer.validated_data.get('Class_name')
            
            Invitation_Code = Unique_code
            teacher = Teacher.objects.get(pk=user.id)
            new_class = Classroom(Class_name = class_name, Subject=Subject, section=section,
                Invitation_Code=Invitation_Code
                )
            new_class.Teacher = teacher
            new_class.save()
            data['Valid'] = "Valid"
        
        
    return Response(data)

@api_view(["POST"])
@permission_classes([])
def pdfCreate(request):
    serializer = pdfCreateSerilizer(data=request.data)
    data = {}
    if serializer.is_valid():
        messages = serializer.save()
        data['Message'] = messages

    return Response(data)

@api_view(["POST"])
@permission_classes([])
def Check_images_AI(request):
    serializer = ImageSerializer(data=request.data)
    data = {}
    if serializer.is_valid():
        mid = serializer.save()
        Message = checkimages(mid)
        data['Message'] = Message
    return Response(data)


def checkimages(mid):
    dataResponse = ''
    known_face_encodings = []
    results =[]
    image_dir = os.path.join(BASE_DIR, 'media/avatar/')
    mypath = os.path.join(BASE_DIR, 'media/check/')

    for image_file in glob.glob(os.path.join(image_dir, '*.jpg')):      
        this_face = face_recognition.load_image_file(image_file) 
        this_face_encodings = face_recognition.face_encodings(this_face)[0]
        known_face_encodings += [this_face_encodings]

    obj = image_verify.objects.get(id = mid)
    url = obj.image.url
    Unknownmypath = BASE_DIR + url

    unknown_image = face_recognition.load_image_file(Unknownmypath) 
    unknown_face_encoding = face_recognition.face_encodings(unknown_image)[0]

    for face_encoding in known_face_encodings:
        results = face_recognition.compare_faces( known_face_encodings,unknown_face_encoding )


#print(image_dir)

src/vclass/templates/sign/Teacherclass.html
{% extends 'sign/index.html' %}

{% block style %}
<title>Classroom | Class</title>
{% endblock %}

{% block content %}

<h2>{{ object.Class_name }}</h2>
<h3>
    {{ object.Subject }}
</h3>
{% for student in students %}
<li>{{ student.First_name }} {{ student.Last_name }}
    <h5>Email: {{ student.Email_address }}</h5>
</li>

{% endfor %}
<hr>
{% if not metarials %}
<ul>
    <li>No activity given Yet</li>
</ul>
{% else %}
<ul>
    {% for work in metarials %}
    <li>{{ work.Description }} | {{ work.title }}</li>
    <a href="{{ work.Pdf.url }}">pdf</a>
    {% endfor %}
</ul>
{% endif %}
<a href="{% url 'portf:pdf-create' object.id %}">Add Task</a>
{% endblock %}

src/vclass/templates/sign/class.html


<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">    <link rel="stylesheet" href="class.css">
    <link rel="stylesheet" href="{% static 'css/class.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    {% block style %}
    <title>Classroom | Class</title>
    {% endblock %}
    
</head>
<body>
  <!-- Navbar -->
  {% block content %}
  <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container-fluid">
      {% if request.user.is_Student %}
      <a class="btn btn-secondary btn-sm" href="{% url 'portf:student-home' %}">Go Back</a>
      {% endif %}
      {% if request.user.is_Teacher %}
      <a class="btn btn-secondary btn-sm" href="{% url 'portf:teacher-home' %}">Go Back</a>
      {% endif %}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item">
            <a class="nav-link active" id="Class" aria-current="page" href="{% url 'portf:teacher-class-view' object.id %}">Class</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="Students" href="{% url 'portf:people' object.id %}">Students</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="Tasks" href="{% url 'portf:task' object.id %}">Tasks</a>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item">
            {% if request.user.is_Teacher %}
                <a style="color: white;" class="nav-link link-button" href="{% url 'portf:pdf-create' object.id %}">Add New Task <i class="fas fa-plus"></i></a>
                {% endif %}
          </li>
        </ul>
        
      </div>
    </div>
  </nav>
  

  <!-- class -->
  <div class="container">
    <div class="back mt-4 px-3 pt-3 height rounded-border row">
      <div class="col-12">
        <h1>{{ object.Class_name }}</h1>
        <p class="fs-6">{{ object.section }}</p>
      </div>
    </div>
    {% if not metarials %}
    <div class="row mt-3 py-5">
        <div  class=" mx-auto custom-border col-10">
          <p class="text-muted"> No Tasks given yet ! </p>
        </div>   
      </div>
      {% else %}
    {% for work in metarials %}
    <div class="row mt-1 py-5">
      <div onclick="window.location='{{  work.get_absolute_url  }}'" class=" mx-auto clickable custom-border col-10">
        <h3>{{ work.title }}</h3>
        <p class="text-muted"> Click here to view details </p>
      </div>   
    </div>
    {% endfor %}
    {% endif %}
  </div>

  
  {% endblock %}
</body>
</html>

src/vclass/templates/sign/create.html
{% extends 'sign/index.html' %}

{% load static %}
{% block styles %}
    <title>Classroom | Create</title>
{% endblock %}

{% block content %}


{% endblock %}

src/vclass/templates/sign/landing.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Home - Brand</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aclonica">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
    <link rel="stylesheet"  href="{%  static  'css/landing.min.css'  %}">

</head>

<body>
    
    <div class="navbar">

        <div class="navbar-brand"> <a style="text-decoration: none;" href="#">Classroom</a> </div>

        <nav>
            <a href="{% url 'portf:register' %}">Sign Up</a>
            <a href="{% url 'portf:login' %}">Login</a>
        </nav>

    </div>

    <div class="hero">
        
        <div class="left">
            <div class="head">
                <h1>Virtual Classroom</h1>
                <p>Join your virtual classroom today ! Sign up for free</p>
            </div>
            <div class="sign-up">
                <a href="{% url 'portf:register' %}">Sign Up</a>
            </div>
        </div>

        <div class="right">
            <img src="{% static 'css/img/illus.svg' %}" alt="some illustration">
        </div>
    </div>

    <div class="features">
        <div class="f-1">
            <i class="fi-xwlux5-lightning-wide"></i>
            <h4>It is fast and easy</h4>
        </div>

        <div class="f-1">
            <i class="fi-xnsux4-computer-desktop-solid"></i>
            <h4>Create Classroom or Join at a press of a button</h4>
        </div>

        <div class="f-1">
            <i class="fi-xwlux4-smartphone-wide"></i>
            <h4>Comes with an Android app</h4>
        </div>
    </div>
    <script defer src="https://friconix.com/cdn/friconix.js"> </script>
</body>

</html>

src/vclass/templates/sign/mailing.html
{% extends 'sign/index.html' %}
{% load static %}
{% block styles %}
<title>Classroom | Mail</title>
<link rel="stylesheet" href="{%  static  'css/bootstrap.min.css'  %}">
<link rel="stylesheet" href="{%  static  'css/mail.css'  %}">
{% endblock %}

{% block content %}
{% if code is not None %}
<span id="myspan" class="message">
  Your code has been added !
  <div>
    <button id="button" onclick="myFunction()" class="btn btn-secondary">close</button>
  </div>
</span>
{% else %}
<span></span>
{% endif %}
<div class="a container-fluid">
  <a class="btn btn-secondary" href="{% url 'portf:teacher-home' %}">Go Back</a>
  <h3>Send Email</h3>
  <div class="row">
    <div class="col-sm-2 col-lg-4"></div>
    <div class="col-sm-8 col-lg-4">
      <form action="{% url 'portf:mailing' %}" method="post">
        <div class="container">
          {% csrf_token %}
          <div><label for="code">Invitation code: </label></div>
          <input type="text" name="Class_code" value="{{ code }}">
          <div><label for="email">E-mail: </label></div>
          <input type="email" name="Email" required>
          <div>
            <input class="btn btn-primary" type="submit" value="send">
          </div>
        </div>
      </form>
      <div class="col-sm-2 col-lg-4"></div>
    </div>
  </div>
</div>

{% if class %}
<div class="container-fluid">
  <h3>All your classes</h3>
  <div class="row">
    {% for code in class %}
    <div class="col-sm-6 col-md-4 col-lg-3">
      <div class="card ">
        <div class="card-body">
          <h5 class="card-title">{{ code.Class_name }}</h5>
          <p class="card-text">{{ code.Subject }} </p>
          <form style = "border:none;" action="{% url 'portf:mailing' %}" method="GET">
          <label for="code">Invitation code:</label>
          <input name="code" type="text" value="{{ code.Invitation_Code }}" id="myInput">
          <input class="btn btn-primary" type="submit" value="Add">
        </form>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% else %}
<div class="container-fluid">
  <h3>No class yet</h3>
</div>

{% endif %}

<script type="text/javascript">
 function myFunction() {
  var element = document.getElementById("myspan");
  element.classList.add("hide");
}
</script>

{% endblock %}

src/vclass/templates/sign/register.html
{% extends 'sign/index.html' %}

{% load static %}
{% block styles %}
<link rel="stylesheet" href="{%  static  'css/regi.css'  %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,600;1,500;1,600&display=swap" rel="stylesheet">

{% endblock %}
{% block content %}



<header>

    <main>
    <section>
    
    <h3>Welcome to the Virtual Classroom</h3>
    
    <h1>Virtual Classroom <span class="change_content"></span></h1>
    
    <p> A collaborative web conferencing tool with online  <br> 
     tutors who want to conduct highly interactive
     live online teaching sessions.</p>
     <a href ="{% url 'portf:student_register' %}" class="btnone"> Register as Student</a>
    
     <a href ="{% url 'portf:teacher_register' %}" class="btntwo"> Register as Teacher</a>
    
    
    </section>
    
    </main>
    
    </nav>
    
    
    </header>


{% endblock %}

src/vclass/templates/sign/task.html
{% extends 'sign/class.html' %}
    {% load static %}
    
    {% block style %}
    <title>Classroom | task</title>
    {% endblock %}

  <!-- Navbar -->
  {% block content %}
  <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container-fluid">
      {% if request.user.is_Student %}
      <a class="btn btn-secondary btn-sm" href="{% url 'portf:student-home' %}">Go Back</a>
      {% endif %}
      {% if request.user.is_Teacher %}
      <a class="btn btn-secondary btn-sm" href="{% url 'portf:teacher-home' %}">Go Back</a>
      {% endif %}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item">
            {% if request.user.is_Student %}
            <a class="nav-link " id="Class" aria-current="page" href="{{ object.get_absolute_url }}">Class</a>
            {% else %}
            <a class="nav-link " id="Class" aria-current="page" href="{% url 'portf:teacher-class-view' object.id %}">Class</a>
            {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link" id="Students" href="{% url 'portf:people' object.id %}">Students</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" id="Tasks" href="{% url 'portf:task' object.id %}">Tasks</a>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item">
            {% if request.user.is_Teacher %}
                <a style="color: white;" class="nav-link link-button" href="{% url 'portf:pdf-create' object.id %}">Add New Task <i class="fas fa-plus"></i></a>
                {% endif %}
          </li>
        </ul>
        
      </div>
    </div>
  </nav>
  

  <!-- class -->
  <div class="container">
    <div class="back my-4 px-3 py-5 rounded-border row">
      <div class="col-12">
          {% if not metarials %}
          <h2 class="text-muted" >No Tasks Yet :)</h2>
          {% else %}
        <h2  >All your tasks at a glance !</h2>
        
      </div>
    </div>
    <div class="row">
        {% for work in metarials %}
    <div class="bg-light border border-warning rounded-bottom my-1 ml-2 p-2 col-3 text-center">
        <h5>{{ work.title }}</h5>
        <p class="font-italic" >
            {{ work.Description }}</p>
    </div>
    {% endfor %}
    {% endif %}
</div>

  </div>

  
  {% endblock %}